### ISSUE TITLE
Allow for a configurable Gitlab url

### ISSUE THREAD

**Issue by pkwiatkowski1** [sigstore/fulcio#1325]
**Description**

Currently the Gitlab issuer's [url field](https://github.com/sigstore/fulcio/blob/main/pkg/identity/gitlabcom/principal.go#L173) that gets included in the certificate's extensions is hardcoded to `gitlab.com`. It would be nice to make this a more dynamic/configurable field to allow for other gitlab installations to easily integrate to a private Fulcio deployment.

**Comment by haydentherapper** [comment]
Check out https://github.com/sigstore/fulcio/pull/1214#issuecomment-1594438846 where we discussed this. The issuer extension (1.3.6.1.4.1.57264.1.8) will contain the private GitLab deployment URL, whereas the other extensions are prefixed with this hardcoded string. This will make policy writing simpler so that you don't need to modify your policy for each GitLab instance, but you can still differentiate using the Issuer extension.

**Comment by pkwiatkowski1** [comment]
Ah, got it. Missed that, thanks!
