### ISSUE TITLE
Load test tool

### ISSUE THREAD

**Issue by lukehinds** [sigstore/fulcio#193]
We need tool to load test fulcio and report those results.

**Comment by mattmoor** [comment]
I believe one of the concerns here is having a scalable OIDC issuer that can be used to issue tokens (and accept Fulcio traffic to verify things).

I was able to stand up a fairly minimal OIDC issuer with just two handlers (and an ephemeral key) for unit testing here: https://github.com/sigstore/fulcio/pull/262/files#diff-445f75dbda6fe7b9191d0b2cb94a621ae7a41eb786d6796540df4c6aa7a38d72R136

I have also played with this adding a third handler to issue tokens, and running it as a Knative service, and if you move the secret generation from boot time to ahead of time in a Secret, then I expect this would scale far beyond what we need.

**Comment by haydentherapper** [comment]
I'll take a look at running a load test, feel free to assign me.

**Comment by haydentherapper** [comment]
I don't think we'll have to worry about a scalable OIDC verifier. We [cache](https://github.com/sigstore/fulcio/blob/3d034fd84371b58e6331da7eaf2b5bf8360dcceb/pkg/config/config.go#L113) the verification keys for OIDC tokens. When making the requests, we'll just cache an OIDC token and use it for each request.

**Comment by haydentherapper** [comment]
Running load test now. As discussed at today's meeting, I'll run it for a short period to not fill the CT logs. Note that I'm hitting Fulcio directly, so I'm not populating the Rekor log.

**Comment by haydentherapper** [comment]
**Methodology:**

I used [Locust](https://locust.io/) for the performance testing. In Python, you create tasks that simulate one request. To start a test, you run a local instance of Locust. For each test run, you can specify the maximum number of requests per second per user (in code), the number of users (in the UI), and the per-second ramp-up to reach the max number of users (in the UI).

I crafted a valid request to create a certificate (Will upload the code shortly). To authenticate with Fulcio, I used a Google OIDC token bound to a service account. The lifetime of token from Sigstore's OIDC instance were too short, whereas Google OIDC tokens have a lifetime of 1 hour. (Note that if we want to run performance tests periodically as part of CI for regression testing, we can use a token from a Github action runner) 

As discussed above, since Fulcio caches the verification keys for OIDC tokens, we do not have to worry about the impact of performance testing on the OIDC provider.

I ran the tests from a VM in us-west1. Note that Fulcio runs in us-central1.

**Tests:**

I ran two tests for around one minute each. As discussed in today's sync, I limited this test to just one minute because we didn't want to fill the production CT log with many test certs. The first test maxed out at 5 QPS, with 5 threads each at 1 QPS. The second test maxed out at 24 QPS, with 24 threads each at 1 QPS.

GCP CA Service has a per-CA request limit of 25 QPS. Since we have only one CA in the CA pool currently, there was no reason to run the test at more than 25 QPS, since we know CA Service will start throttling.

**Results:**


![total_requests_per_second_1639528091](https://user-images.githubusercontent.com/8418760/146115172-3dc313ff-3408-4f20-8e85-514061dfb26b.png)
![response_times_(ms)_1639528092](https://user-images.githubusercontent.com/8418760/146115241-0de09b8a-6921-41be-a922-b9f7d4fdad11.png)

[Report for 25 QPS test run (PDF)](https://github.com/sigstore/fulcio/files/7716184/fulcio-25qps-report.pdf)

No errors with either test run. P95 response time was around 300ms for the 5 QPS test, and around 450ms for the 24 QPS test.

**Potential AIs:**

* Write up doc on how to scale past 25 QPS. Do we want more than 25 QPS? If so, we need to add additional CAs to the CA pool ([See documentation](https://cloud.google.com/certificate-authority-service/docs/ca-pool#higher-qps). A CA pool supports up to 100 QPS, so we will need to add 3 additional DevOps-tier CAs. This would require adding additional targets to the TUF root however.
* Add optional rate limiting middleware to Fulcio, which we can enable for Fulcio instances that use GCP CA Service.
* Investigate increase in P95 to determine if there's a bottleneck.
* Run this test again against a staging instance.

cc @asraa @priyawadhwa @bobcallaway

**Comment by haydentherapper** [comment]
This is complete.
