### ISSUE TITLE
Support API for fetching the SCT key

### ISSUE THREAD

**Issue by mattmoor** [sigstore/fulcio#330]
**Description**

This came up in the `cosigned` API task force.

Essentially, to verify against a custom fulcio root we need both the root and SCT certs.  We added a way to fetch the former, but not the latter.

Ideally we would be able to specify alternative Fulcio roots via the API in the simple case, and only need to inline keys for air-gap scenarios.

cc @dlorenc @bobcallaway for any thoughts / gotchas

**Comment by mattmoor** [comment]
cc @vaikas as well

**Comment by vaikas** [comment]
I think this would basically make us explicitly trust Fulcio to not lie about the CT public key. My understanding is that we have to be able to 'trust but verify' what Fulcio does, and the way to do this is to take the SCT and validate it against the public key of the CTLog and having Fulcio supply that to us seems like a problem. By having the key to the verifier be OOB makes it so that we can verify that Fulcio actually submitted the entry to CTLog.

**Comment by dlorenc** [comment]
Yeah - we can serve it from the endpoint but just need to clearly instruct clients to store it so they can TOFU from there, instead of just blindly trusting it each time.

**Comment by vaikas** [comment]
What does TOFU mean? 🤣

**Comment by dlorenc** [comment]
Hah sorry! Trust on first use!

**Comment by haydentherapper** [comment]
Can we add a method to the CT log API to provide the SCT key by request?

**Comment by vaikas** [comment]
@haydentherapper it might be more involved to add it there, given:
https://datatracker.ietf.org/doc/html/rfc6962

But, perhaps I'm misunderstanding something.

**Comment by haydentherapper** [comment]
@vaikas Good point, this is explicitly called out here - https://datatracker.ietf.org/doc/html/rfc6962#section-5.2

It makes sense that the log will not distribute its verification key, that it's expected there's some out-of-band distribution of it.

**Comment by haydentherapper** [comment]
Going to close this, as it's not something we'd add to Fulcio. Trillian or CT could add an API for this, but they may not want to since it risks insecure design patterns, such as fetching the public key from the log before verifying the entry. They may want to force out-of-band delivery of the verification key.
