### ISSUE TITLE
Figure out how to handle the CT log proofs in clients

### ISSUE THREAD

**Issue by dlorenc** [sigstore/fulcio#42]
The simplest way seems to be the "precertificate" method, here: https://letsencrypt.org/2018/04/04/sct-encoding.html

We request two certs from the CA - a "precertificate" and the real one. The precertificate is "poisoned" with a special bit set: https://github.com/google/certificate-transparency-go/blob/v1.1.1/x509/x509.go#L1208

Then that is included in the log. When that is finished, the SCT (signed cert timestamp) is embedded in the final cert. The certs are identical, except the poison bit is removed and the SCT is added.

That way clients can verify the cert is in the log without making any requests.

**Comment by priyawadhwa** [comment]
So for this to work, the precert we get from the CA has to be identical to the cert we get from the CA except for the one extension. I closed #55 because it looks like the GCP CA doesn't let you specify the serial number of the cert, so the numbers on the precert and the cert can't match 😞 

Closed the PR for now, but possible solutions:

1. If we set up an intermediary CA that allows us to specify serial numbers, we can probably get this to work

and that's pretty much it 😅  If anyone has any other ideas that would be great! 

For future reference:
- [validation function I was using](https://github.com/google/certificate-transparency-go/blob/109466f2efc1e5eeb78c9bc25cbc6069b8afa40b/ctutil/ctutil.go#L84)

**Comment by dlorenc** [comment]
cc @mmalone any ideas here? Might be time to read all that stuff you sent me about setting up the step CA :)

**Comment by haydentherapper** [comment]
Priya, mind if I assign this to myself? I ended up writing a doc on embedding SCTs in certificate, and then found this issue and the CA Service problem.

**Comment by priyawadhwa** [comment]
For sure!

**Comment by haydentherapper** [comment]
When we switch over to embedded SCTs, it's going to be a breaking change. I thought providing the SCT in both the header and embedded would be fine, but it's not sufficient. The SCT is generated using the precertificate, which doesn't contain the embedded SCT. The current version of Cosign doesn't know to reconstruct the certificate without the embedded SCT, so signature verification fails (it's just a flag in the verification function).

I just need to update Cosign to handle embedded SCTs, but users must update Cosign in order to call Fulcio once we start embedding SCTs.

fyi @dlorenc @bobcallaway - Any concerns? We'll just need to cut a new release of Cosign before switching Fulcio over to the new intermediate.
