### ISSUE TITLE
Question/Idea: Reverse Domain Name Notation Identity via DNS and Public/Private Keys

### ISSUE THREAD

**Issue by martinsstuff** [sigstore/fulcio#551]
(I have only been following Sigstore for a couple weeks so apologies if this has already been discussed somewhere!)

## My thoughts

As a big fan of Let's Encrypt, I have been very interested in Sigstore ever since I found out about it. However, I always found the email-via-OIDC system quite limited. I see there are multiple discussions about this topic, but so far they all still seem focused around improving the email-based system (which I still fully support!).

My idea is to offer the option of the quite universally recognized identity of a (sub-)domain to sign things. If I imagine a future where Sigstore, or a similar service, truly becomes the "Let's Encrypt of Code Signing", I feel like a domain would be much more intuitive to see in, let's say, a Windows UAC prompt.

## Concept:

0. User owns a domain and has control over DNS records.
1. User generates a public/private key pair.
2. User published public key via a TXT record on their domain. (Example: `_fulcio-pubkey.myproduct.example.com`)
3. User wants to sign something and attempts to prove their identity to Fulcio with help of the private key.
4. The TXT record with the public key is checked by multiple geographically separate servers (Similar to how Let's Encrypt does it)
5. If there are no discrepancies with DNS, the identification attempt is checked against the public key.
6. If everything checks out, signing commences and the identity is, for the example: `com.example.myproduct`

## Comparison to email based signing:

Pros:
- Vendor neutral
- Recognizable reverse domain name notation convention
- Easy separate signing of different projects. Examples: `com.example.myproductA`, `com.example.myproductB`, or even `com.example.myproduct.testing`, applications can be configured to only accept files signed for the release version of the intended product, more easily recognizable to users than some email address.
- Account at DNS provider may be better secured and audited than, for instance, Microsoft or GitHub accounts, which are frequently accessed by the user.

Neutral:
- Significantly different to current email-based identities, but both formats should be able to coexist.

Cons:
- Vulnerable to compromise of DNS account or provider.
- Private key security entirely in the hands of the user.
- User needs get a domain and keep paying for it (free domains exist but they are really sketchy)

Potential for better security:
- Some type of key rotation mechanism.
- Some kind of TTL/caching of the public key to "bridge" DNS compromise (instant revocation method would be required).

**Comment by dlorenc** [comment]
Hey! Thanks for the issue. I think we might already support something similar to what you're describing through SPIFFE and SPIRE. It's documented here: https://github.com/sigstore/fulcio/blob/e88278c03c1593ea3f6dc68d7c7144e545a1fb3b/docs/oidc.md#L27

Note that it still goes through the OIDC flow, but it doesn't use emails. You can expose a SPIRE OIDC endpoint at a URL, and we use the DNS from that URL to verify ownership. Then we issue certificates with SPIFFE SVIDs as the subject, rather than email addresses.

**Comment by martinsstuff** [comment]
@dlorenc This looks interesting but since I don't already use SPIFFE it seems like it might be a big setup just to sign code, but I'll have to try it out.

**Comment by nsmith5** [comment]
I like the idea of a domain as subject but I agree its a bit of work to set up a SPIFFE trust domain to get this working. Instead of posting a public key and needing to maintain that private key over time (Like DKIM when you manage an email server) it might be better to think about supporting the DNS challenge ACME challenge like LetEncrypt and use short lived certificates like we currently do.

**Comment by haydentherapper** [comment]
While it is some work to set up SPIFFE/SPIRE and OIDC, it encourages better security practices than self-management of the private key for a DNS-based approach. I'd love to see folks try out SPIFFE and see where the pain points are, and maybe we can help with tooling to make it simpler to set up.

**Comment by haydentherapper** [comment]
Closing, would recommend looking into SPIFFE
